# Generated by Django 6.0.4 on 2026-09-01 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_moderationlogentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlevote',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Article vote', 'verbose_name_plural': 'Article votes'},
        ),
    ]
